image: texlive/texlive:latest

build:
  script:
    - latexmk -pdf -cd -output-directory=../../out -aux-directory=../../out src/FinalResearchArticle/FinalResearchArticle.tex
    - latexmk -pdf -cd -output-directory=../../out -aux-directory=../../out src/SoftwareDevelopmentReport/SoftwareDevelopmentReport.tex
  artifacts:
    paths:
      - 'out/*.pdf'
